version: '3.7'
services:
    db:
        image: mysql:8
        container_name: bct-db
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        command: ['--skip-log-bin', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci', '--sql_mode=STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION']
        volumes:
            - bct-database:/var/lib/mysql
            - ./database-schema.sql:/docker-entrypoint-initdb.d/schema.sql:ro
        networks:
            - bct-net
            
    dbadmin:
        image: phpmyadmin/phpmyadmin
        container_name: bct-dbadmin
        restart: unless-stopped
        environment:
            PMA_HOST: db
            UPLOAD_LIMIT: 1000000000
        ports:
            - '${PHPMYADMIN_PORT}:80'
        depends_on:
            - db
        networks:
            - bct-net

    api:
        image: node:latest
        container_name: bct-api
        restart: unless-stopped
        working_dir: /app
        command: >
            sh -c '
                npm install --silent
                node api.js
            '
        environment:
            MYSQL_HOST: db
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
            REACT_APP_ONION_EXPLORER_HOST: ${REACT_APP_ONION_EXPLORER_HOST}
        ports:
            - "${REACT_APP_API_PORT}:3001"
        depends_on:
            - db
        volumes:
            - ./api:/app
        networks:
            - bct-net

    frontend:
        image: node:latest
        container_name: bct-frontend
        restart: unless-stopped
        working_dir: /app
        command: >
            sh -c '
                # export PATH="/app/node_modules/.bin:$PATH"
                npm install --silent
                # echo "Starting site in production mode...";
                # npm run build
                # yarn serve;
                echo "Starting site in development mode...";
                yarn start
            '
        environment:
            REACT_APP_ONION_EXPLORER_HOST: ${REACT_APP_ONION_EXPLORER_HOST}
            REACT_APP_PUBLIC_FRONTEND_URL: ${REACT_APP_PUBLIC_FRONTEND_URL}
            REACT_APP_FRONTEND_PORT: ${REACT_APP_FRONTEND_PORT}
            REACT_APP_PUBLIC_API_URL: ${REACT_APP_PUBLIC_API_URL}
            REACT_APP_API_PORT: ${REACT_APP_API_PORT}
        ports:
            - "${REACT_APP_FRONTEND_PORT}:3000"
        volumes:
            - ./frontend:/app
        networks:
            - bct-net

    lookup:
        image: python:3
        container_name: bct-lookup
        restart: unless-stopped
        working_dir: /app
        command: >
            sh -c '
                apt-get update && apt-get install -y build-essential libsystemd-dev
                pip install --quiet -r requirements.txt
                python3 -u lookup.py
                tail -F anything
            '
        environment:
            MYSQL_HOST: db
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
            REACT_APP_ONION_EXPLORER_HOST: ${REACT_APP_ONION_EXPLORER_HOST}
        depends_on:
            - db
            - api
        volumes:
            - ./lookup:/app
        networks:
            - bct-net

volumes:
    bct-database:

networks:
    bct-net:
        name: bct-net
        driver: bridge
